### ISSUE TITLE
Clustalo output missed by trimal

### ISSUE THREAD

**Issue by TomHarrop** [chrisjackson-pellicle/ParaGone#10]
Me again :S

I'm getting an empty trimal output folder (`03_alignments_trimmed`) when I run `check_and_align` with `--use-clustal`

From an extremely quick peek I wonder if the following f-string needs to have ".aln" appended? The clustalo results are in the folder `01_input_paralog_fasta_with_sanitised_filenames_clustal` with names like `5620.fasta`

https://github.com/chrisjackson-pellicle/ParaGone/blob/a59369e2bdf5d3e0351ea2e6b5a10ec1e74a4487/paragone/align_and_clean.py#L603

**Comment by chrisjackson-pellicle** [comment]
Gah, sorry about that. Yep, that and a few other issues with the `--use_clustal` pathway. They should be fixed in v1.1.3. 

If `--use_clustal` is provided, the clustal alignments will now be in directory `02_alignments_clustal`, rather than `01_input_paralog_fasta_with_sanitised_filenames_clustal`.

I think I've tested all the various permutations of the options, but famous last words. I'll write some proper integration tests.

Cheers,

Chris

**Comment by TomHarrop** [comment]
Thanks, my tests passed using clustalo with 1.1.3. Will try it on some real data next week.
